---
# tasks file for tomcat-ansible-role

- name: Tomcat - configure - ${catalina.base}/conf files
  template:
    src: "conf/{{ item.src }}"
    dest: "{{ catalina_base }}/conf/{{ item.dest }}"
    group: "{{ tomcat_group }}"
    owner: "{{ tomcat_runtime_user }}"
    mode: "{{ tomcat_file_mode }}"
  loop:
    - { src: "{{ tomcat_template_server }}", dest: "server.xml" }
    - { src: "context.xml.j2", dest: "context.xml" }
    - { src: "logging.properties.j2", dest: "logging.properties" }
    - { src: "web.xml.j2", dest: "web.xml" }
  notify: Tomcat restart

- name: Tomcat - configure - JVM Security Manager
  template:
    src: "{{ catalina_policy_template }}"
    dest: "{{ catalina_base }}/conf/catalina.policy"
    group: "{{ tomcat_group }}"
    owner: "{{ tomcat_runtime_user }}"
    mode: "{{ tomcat_file_mode }}"
  notify: Tomcat restart
  when: catalina_policy

- name: Tomcat - configure - user roles
  block:
    - name: Tomcat - configure - get user roles to be enabled
      set_fact:
        tomcat_user_roles: "{{ (tomcat_user_roles + item.roles.split(',')|list)|unique }}"
      with_items:
        - "{{ tomcat_users }}"

    - name: Tomcat - configure - prepare tomcat-users.xml
      template:
        src: "conf/{{ tomcat_template_users }}"
        dest: "{{ catalina_base }}/conf/tomcat-users.xml"
        group: "{{ tomcat_group }}"
        owner: "{{ tomcat_runtime_user }}"
        mode: "{{ tomcat_file_mode }}"
      notify: Tomcat restart
  when: tomcat_users | length > 0
