---
# tasks file for tomcat-ansible-role

- name: Tomcat - install and configure server
  block:
    - name: Tomcat - install - check if Tomcat is already installed
      stat:
        path: "{{ system_base }}/apache-tomcat-{{ tomcat_version }}"
      register: _is_installed

    - name: Tomcat - install server
      include_tasks: install.yml
      when: not _is_installed.stat.exists or tomcat_force_install

    - name: Tomcat - make CATALINA_BASE folder structure
      file:
        group: "{{ tomcat_group }}"
        owner: "{{ tomcat_runtime_user }}"
        mode: "{{ tomcat_dir_mode }}"
        path: "{{ item }}"
        recurse: true
        state: directory
      loop:
        - "{{ catalina_base }}"
        - "{{ catalina_base }}/conf"
        - "{{ catalina_base }}/lib"
        - "{{ catalina_base }}/logs"
        - "{{ catalina_base }}/webapps"
        - "{{ catalina_base }}/temp"

    - name: Tomcat - configure application server
      include_tasks: configure.yml

    - name: Tomcat - generate self-signed certificate
      include_tasks: "ssl.yml"
      when: tomcat_ssl_generate_cert

    - name: Tomcat - update `systemd` configuration
      include_tasks: "systemd.yml"
      when: tomcat_service_enabled

    - name: Tomcat - set return facts
      set_fact:
        catalina_home: "{{ catalina_home }}"
        tomcat_version: "{{ tomcat_version }}"
  when: tomcat_state == "present"

- name: Tomcat - uninstall server
  include_tasks: uninstall.yml
  when: tomcat_state == "absent"
