FROM ubuntu:focal

ARG DEBIAN_FRONTEND=noninteractive

# hadolint ignore=DL3008
RUN apt-get update && \
  apt-get install --no-install-recommends -y ansible systemd && \
  rm -rf /var/lib/apt/lists/*

# TODO: not available for `focal` at https://launchpad.net/~ansible/+archive/ubuntu/ansible - 2020-06-07
# RUN apt-add-repository --yes --update ppa:ansible/ansible && \
#   apt-get install -y ansible

RUN echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts

ENTRYPOINT ["/bin/systemd"]
