FROM debian:stretch-backports

ARG DEBIAN_FRONTEND=noninteractive

# Install Ansible
# hadolint ignore=DL3008
RUN apt-get update && \
  apt-get dist-upgrade -o Dpkg::Options::="--force-confnew" -y && \
  apt-get install --no-install-recommends -t stretch-backports -o Dpkg::Options::="--force-confnew" -y ansible systemd && \
  rm -rf /var/lib/apt/lists/*

# Install Ansible inventory file
RUN mkdir -p /etc/ansible && echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts

ENTRYPOINT ["/bin/systemd"]
